name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for ARM64
      run: npm i && npm run docker:push-arm
    - name: Build the Docker image for AMD64
      run: npm i && npm run docker:push-amd

