name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn && yarn add ffmpeg-binaries

      - name: Build artifact
        run:  npx esbuild index.js --bundle --platform=node --minify --external:./config.json --external:@ffmpeg-installer/ffmpeg --external:@node-ffmpeg/node-ffmpeg-installer --outfile=bundle.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: BDL-Server
          path: bundle.js
